sonar.projectKey=campus-events
sonar.projectName=CampusEvents API
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,reports/**
sonar.coverage.exclusions=src/server.js,src/config/db.js
sonar.sourceEncoding=UTF-8